#!/bin/sh
# prerm script for nvidia-settings
#
# Copyright (C) 2011 Canonical Ltd
# Authors: Alberto Milone


PACKAGE_NAME=nvidia-settings

case "$1" in
	remove)
		update-alternatives --remove nvidia_setting_conf /usr/lib/nvidia-settings/ld.so.conf

		# Trigger gmenu so as to update the gnome menu
		dpkg-trigger --by-package=$PACKAGE_NAME gmenucache || true

		# explicit ldconfig due to alternatives
		ldconfig
	;;
esac

#DEBHELPER#
